### PR TITLE
Problem: Send / Recv API is confusing and some problems solved are only hypothetical

### PR DESCRIPTION
**Pull request by taotetek**
Danger, Will Robinson!  Breaking Changes!

* Get rid of various "String" functions that translate from []byte to string, as translation is simple in go. These functions were solving hypothetical problems.  
* "Frame" in the API terms is now considered to be a []byte
* "Message" in the API terms is now considered to be a [][]byte
* Got rid of various different ways of sending and receiving single message parts and multi-part message, reduced to SendFrame, SendMessage, RecvFrame, RecvMessage
* Refactored all tests appropriately

### CODE REVIEW

**Comment by PSG-Luna** [comment]
Code loosk good, waiting for travis before merging

**Comment by taotetek** [comment]
Failed! Meh - checking.

**Comment by taotetek** [comment]
Aha - I hadn't changed the perf test code in cmd/ - will do.

**Comment by taotetek** [comment]
@PSG-Luna all clear to merge when you're around again

**Pull request merged**
