### PR TITLE
Problem: Travis CI slowed down by build-dependencies

### PR DESCRIPTION
**Pull request by bluca**
Solution: use pre-built packages from OBS

~1 minute 10 seconds vs ~5 minutes 30 seconds :-)

### CODE REVIEW

**Comment by taotetek** [comment]
@bluca  this broke the build - zbeacon is failing every run, I'm going to send a revert.

**Comment by taotetek** [comment]
@bluca or maybe I broke the  build, hah - looking

**Comment by taotetek** [comment]
@bluca it was me :)  - the new build times are GREAT.

**Comment by bluca** [comment]
eheh no worries

**Pull request merged**
